AYS-64 | The driver error has been resolved.
afet-yonetim-sistemi/ays-fe-ui-automation pull request #24
Opened 2024-01-24 19:33 UTC by cagla88

2024-01-24 19:38 UTC, agitrubard requested changes

2024-01-24 19:38 UTC, agitrubard commented on src/test/java/utilities/DriverClass.java
> +            }
Kod formatlama yapılabilir, bu sayede kodun formatı düzgün olduğunda daha okunaklı hâle getiriliyor. `threadDriverName.get()==null` yerine `threadDriverName.get() == null` şeklinde olması gerekiyor. Bu durumda kısa yollar ile formatlama veya commit atmadan önce formatlama yapılabiliyor. 

Kaynak olarak https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html dokümanı incelebilir.

2024-01-29 22:37 UTC, cagla88 reviewed
@agitrubard kodlar düzenlendi review edip merge'leyebilir misiniz?

2024-01-30 15:13 UTC, agitrubard approved these changes

2024-01-30 15:31 UTC, merged