Feature/ays 120/logout function
afet-yonetim-sistemi/ays-fe-ui-automation pull request #26
Opened 2024-02-11 23:11 UTC by nakcay

## Pull Request

**Description:**
Provide a brief description of the changes in this pull request.

**Related Issue:**
Closes #[Issue Number]

**Changes Made:**
List the changes you made in this pull request.

**Additional Information:**
Add any additional information that might be relevant to reviewers.

## Checklist
- [ ] I have read and followed the [contribution guidelines](README.md#contributing) for this project.
- [ ] I have added tests (if applicable).
- [ ] All tests are passing.
- [ ] I have updated the documentation (if necessary).

## Reviewer Instructions
Provide instructions or guidelines for reviewers to follow when assessing your pull request.

2024-02-12 09:21 UTC, agitrubard requested changes

2024-02-12 09:21 UTC, agitrubard commented on src/test/java/step_definitions/Logout.java
> +}
Kod formatlamalarında problem var gibi duruyor, formatlama yapmamızda ve boşluklara dikkat etmemizde fayda var

2024-02-12 09:21 UTC, agitrubard commented on src/test/java/pages/LogoutPOM.java
> +}
Kod formatlamalarında problem var gibi duruyor, formatlama yapmamızda ve boşluklara dikkat etmemizde fayda var

2024-02-13 12:44 UTC, agitrubard requested changes
Pull request başlığını standartlara uygun bir şekilde güncelledikten sonra mergeleyebiliriz ✅

2024-02-13 23:03 UTC, Nbhtozcn approved these changes

2024-02-13 23:28 UTC, cagla88 approved these changes

2024-02-14 14:48 UTC, agitrubard approved these changes

2024-02-14 14:48 UTC, merged