AYS-166 | Added one step into UsersDelete.feature file and doubleClic…
afet-yonetim-sistemi/ays-fe-ui-automation pull request #30
Opened 2024-03-09 22:37 UTC by TekinMerve

## Pull Request
**Description:**
Added one step into UsersDelete.feature file
Added doubleClick utility method in AysPageActions

**Related Issue:**
Closes #[AYS-166]

2024-03-10 06:15 UTC, agitrubard requested changes

2024-03-10 06:15 UTC, agitrubard commented on src/test/java/org/ays/browser/AysPageActions.java
> +        new Actions(this.webDriver).doubleClick(element).build().perform();
```suggestion
        this.actions.doubleClick(element).build().perform();
```

2024-03-10 21:49 UTC, TekinMerve commented
Selam @agitrubard . Önerdiğiniz değişikliği commit ettim ve mevcut PR'a bu değişiklik yansıdı. Uygun bir zamanınızda review&merge edebilir misiniz?

2024-03-11 14:33 UTC, agitrubard approved these changes

2024-03-11 14:33 UTC, merged