AYS-191/ApplicationRegistration
afet-yonetim-sistemi/ays-fe-ui-automation pull request #36
Opened 2024-03-14 19:58 UTC by yvzcnr

## Pull Request

**Description:**
Provide a brief description of the changes in this pull request.

**Related Issue:**
Closes #[Issue Number]

**Changes Made:**
List the changes you made in this pull request.

**Additional Information:**
Add any additional information that might be relevant to reviewers.

## Checklist
- [ ] I have read and followed the [contribution guidelines](README.md#contributing) for this project.
- [ ] I have added tests (if applicable).
- [ ] All tests are passing.
- [ ] I have updated the documentation (if necessary).

## Reviewer Instructions
Provide instructions or guidelines for reviewers to follow when assessing your pull request.

2024-03-15 17:55 UTC, agitrubard requested changes

2024-03-15 17:55 UTC, agitrubard commented on src/test/java/org/ays/pages/SuperAdminPOM.java
> +
```suggestion

```

2024-03-15 17:55 UTC, agitrubard commented on src/test/java/org/ays/step_definitions/SuperAdminRegistrationFilter.java
> +    private final SuperAdminPOM superAdminPOM = new SuperAdminPOM();
Bu kısım için eğer step definition'ları mı örnek almıştınız?

2024-03-15 17:55 UTC, agitrubard commented on src/test/java/org/ays/feature/SuperAdminRegistrationFilter.feature
> +    Then Click filter button
```suggestion
    Then Click filter button
    
```

2024-03-15 17:55 UTC, agitrubard commented on src/test/java/org/ays/configuration/AysConfigurationProperty.java
> +        public static class SuperAdminUserOne {
```suggestion
        }
        
        public static class SuperAdminUserOne {
```

2024-03-15 18:42 UTC, cagla88 requested changes

2024-03-15 18:42 UTC, cagla88 commented on src/test/java/org/ays/step_definitions/SuperAdminRegistrationFilter.java
> +    @When("Enter the super admin username and password")
Selamlar, method isimleriyle senaryo adımları aynı olmalıdır. Bu şekilde diğer testler ile çakışmaya sebep verecektir.

2024-03-15 18:45 UTC, cagla88 requested changes

2024-03-15 18:45 UTC, cagla88 commented on src/test/java/org/ays/step_definitions/SuperAdminRegistrationFilter.java
> +}
Selamlar, method isimleriyle senaryo adımları aynı olmalıdır. Bu şekilde diğer testler ile çakışmaya sebep olur.

2024-03-18 16:45 UTC, cagla88 approved these changes

2024-03-18 18:07 UTC, agitrubard approved these changes

2024-03-18 18:08 UTC, agitrubard requested changes
Çalışmayan testler var ve pull request başlığını standartlara uygun olarka düzenleyebilir misiniz?

2024-03-19 20:59 UTC, agitrubard approved these changes

2024-03-19 21:06 UTC, agitrubard requested changes
Testlerin çalışmaması durumu hâlâ devam etmekte

2024-03-20 19:22 UTC, agitrubard approved these changes

2024-03-20 19:23 UTC, agitrubard requested changes

2024-03-20 19:23 UTC, agitrubard commented on src/test/java/org/ays/runners/RunnerForRegressionTest.java
> +)
@cagla88 eğer burada ortak bir şey varsa bütün runner'larda çalışması için Abstract Class'a eklememiz daha iyi olabilir

2024-03-20 19:33 UTC, agitrubard approved these changes

2024-03-20 19:34 UTC, cagla88 approved these changes

2024-03-20 19:35 UTC, merged