AYS-206 | Fixing ignored tests.
afet-yonetim-sistemi/ays-fe-ui-automation pull request #39
Opened 2024-04-03 11:20 UTC by cagla88

UsersCreate Test Cases Have Been fixed.

2024-04-03 11:29 UTC, agitrubard approved these changes

2024-04-04 06:38 UTC, agitrubard requested changes

2024-04-04 06:38 UTC, agitrubard commented on src/test/java/org/ays/step_definitions/UsersEdit.java
> +        if (usersPOM.getStatusDropdown().getText().equalsIgnoreCase("Passive")) {
Buradaki textlerin ignoreCase değil de doğrudan equals olması gerekmiyor mu? Çünkü text değişmişse bunu fark edebiliyor olmamız gerekiyor

2024-04-04 06:38 UTC, agitrubard commented on src/test/java/org/ays/step_definitions/UsersEdit.java
> +        if (usersPOM.getStatusDropdown().getText().equalsIgnoreCase("Active")) {
Buradaki textlerin ignoreCase değil de doğrudan equals olması gerekmiyor mu? Çünkü text değişmişse bunu fark edebiliyor olmamız gerekiyor

2024-04-04 14:33 UTC, cagla88 commented on src/test/java/org/ays/step_definitions/UsersEdit.java
> +        if (usersPOM.getStatusDropdown().getText().equalsIgnoreCase("Passive")) {
burada bunu büyük küçük harfe duyarlı olmasın diye ekledim. Active veya passive dışında tek bir harfi bile değişse zaten hata verecektir. Amaç burada el ile yazılırken büyük küçük harfe duyarlı olmamasıydı. Ama yinede değişsin derseniz değiştirebilirim

2024-04-05 17:25 UTC, agitrubard requested changes

2024-04-05 17:25 UTC, agitrubard commented on src/test/java/org/ays/browser/AysPageActions.java
> +    }
WebDriverWait kullanamıyor muyuz?

2024-04-05 17:26 UTC, agitrubard commented on src/test/java/org/ays/step_definitions/UsersEdit.java
> +        if (usersPOM.getStatusDropdown().getText().equalsIgnoreCase("Passive")) {
`equalsIgnoreCase()` metodu büyük küçük harf duyarlı olsun diye değil, duyarsız olsun diye kullanılıyor

2024-04-05 17:51 UTC, cagla88 commented on src/test/java/org/ays/step_definitions/UsersEdit.java
> +        if (usersPOM.getStatusDropdown().getText().equalsIgnoreCase("Passive")) {
aynı şeyi söyledim bende aksini söylemedim :) tmmdır dediğiniz gibi düzenlerim

2024-04-05 18:16 UTC, cagla88 commented on src/test/java/org/ays/step_definitions/UsersEdit.java
> +        if (usersPOM.getStatusDropdown().getText().equalsIgnoreCase("Active")) {
istediğiniz değişiklikleri yaptım. Review edip mergeleyebilir miyiz? UsersEdit testini açtığım bug issue teste gelince o issue üzerinde düzenlerim eğer uygunsa sizin içinde

2024-04-05 18:37 UTC, cagla88 commented on src/test/java/org/ays/browser/AysPageActions.java
> +    }
onlarıda kullandım birden fazla wait condition eklememe rağmen test geçmeyince mecbur bunu da kullandım.

2024-04-06 07:23 UTC, agitrubard commented on src/test/java/org/ays/step_definitions/UsersEdit.java
> +        if (usersPOM.getStatusDropdown().getText().equalsIgnoreCase("Passive")) {
Şu konuda anlaşamadık sanırım, ekranda `Passive` yazıyorsa, burada da `Passive` yazması lazım. Ki bu yazı `PASSIVE` olarak değişirse anlayabilelim. Aslında büyük küçük harf duyarlı olması gerekiyor yani. Duyarsız olmaması lazım.

2024-04-06 07:24 UTC, agitrubard approved these changes

2024-04-06 09:22 UTC, merged